head /proc/self/mountinfo
12210 12209 254:12 / / ro,relatime master:1 - erofs /dev/block/dm-12 ro,seclabel,user_xattr,acl,cache_strategy=readaround
12211 12210 0:17 / /dev rw,nosuid,relatime master:2 - tmpfs tmpfs rw,seclabel,size=1866176k,nr_inodes=466544,mode=755
12212 12211 0:18 / /dev/pts rw,relatime master:3 - devpts devpts rw,seclabel,mode=600,ptmxmode=000
12213 12211 0:24 / /dev/blkio rw,nosuid,nodev,noexec,relatime master:16 - cgroup none rw,blkio
12214 12211 0:26 / /dev/cpuctl rw,nosuid,nodev,noexec,relatime master:18 - cgroup none rw,cpu
12215 12211 0:27 / /dev/cpuset rw,nosuid,nodev,noexec,relatime master:19 - cgroup none rw,cpuset,noprefix,release_agent=/sbin/cpuset_release_agent
12216 12211 0:28 / /dev/memcg rw,nosuid,nodev,noexec,relatime master:20 - cgroup none rw,memory
12217 12211 0:31 / /dev/binderfs rw,relatime master:23 - binder binder rw,max=1048576,stats=global
12218 12211 0:35 / /dev/usb-ffs/adb rw,relatime master:27 - functionfs adb rw
12219 12211 0:36 / /dev/ffs-diag rw,relatime master:28 - functionfs diag rw
~ $../src/Makefile